FROM php:7.4-cli
RUN docker-php-ext-install pdo pdo_mysql sockets
RUN curl -sS https://getcomposer.org/installer​ | php -- \
    --install-dir=/usr/local/bin --filename=composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN apt-get update && apt-get install -y zlib1g-dev libpng-dev libzip-dev
RUN docker-php-ext-install zip
RUN docker-php-ext-install gd
WORKDIR /app
COPY . .
# RUN composer install
# RUN composer update
