FROM php:5.6-cli
RUN docker-php-ext-install pdo pdo_mysql sockets
RUN curl -sS https://getcomposer.org/installer --2016-09-11 | php -- --install-dir=/usr/local/bin --filename=composer
COPY --from=composer:1.6.5 /usr/bin/composer /usr/bin/composer
# RUN apt-get update && apt-get install -y zlib1g-dev libpng-dev libzip-dev
# RUN docker-php-ext-install zip
# RUN docker-php-ext-install gd
WORKDIR /app
COPY . .
# RUN composer install
# RUN composer update
